import React from "react";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata = {
  title: "Julkar Reedoy",
  image: "favicon.ico",
  //favicon generated by Google Gemini
  description: "My name is Julkar and welcome to my page :)",
};

// eslint-disable-next-line react/prop-types
export default function RootLayout({ children }) {
  const currentPage = "home";
  return (
    <html lang="en">
      <body>
        <Navbar page={currentPage} />
        <div className="wrap  min-h-screen">
          <main>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
